// Mock API responses shaped exactly like the frozen DynamoDB data model.
// Replace fetch calls with real endpoints once Person 3's API is live.

export const MOCK_REQUESTS = [
  // --- Low-risk renewal, no flags ---
  {
    request_id: "aaa-001",
    status: "FlagsComputed",
    created_at: "2026-07-14T10:00:00Z",
    updated_at: "2026-07-14T11:00:00Z",
    requestor: {
      requested_for_name: "Jane Smith",
      requested_for_phone: "619-555-0101",
      requested_for_email: "jsmith@sdsu.edu",
      department: "College of Sciences",
      user_types: ["Faculty", "Staff"],
      scope_of_usage: "Research Lab",
      software_name: "ResearchTrack Pro",
      use_description: "Track lab experiment data and manage research team tasks",
      vendor_website: "https://researchtrackpro.com",
      software_term: "1yr",
      estimated_spend: 4500,
      purchase_type: "renewal",
      funding_source: "SDSU Research Foundation",
      college_division: "College of Sciences",
      existing_requisition: false,
      needs_install_help: false,
      notify_list: ["jsmith@sdsu.edu"],
      additional_details: "Used by 5 grad students and 2 faculty members.",
    },
    it_review: {
      estimated_users: "1-30",
      interaction_method: ["Computer"],
      software_category: "Cloud",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "not_sure",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: "https://researchtrackpro.com/privacy",
    },
    flags: {
      ati_flag: false,
      ati_flag_reason: "Under 30 users, Research Lab scope does not trigger ATI",
      security_flag: false,
      security_flag_reason: "No sensitive data categories identified",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "Low",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
  },

  // --- High-risk new software, all three flags triggered ---
  {
    request_id: "bbb-002",
    status: "UnderStaffReview",
    created_at: "2026-07-13T09:00:00Z",
    updated_at: "2026-07-14T08:00:00Z",
    requestor: {
      requested_for_name: "Mark Torres",
      requested_for_phone: "619-555-0202",
      requested_for_email: "mtorres@sdsu.edu",
      department: "Student Affairs",
      user_types: ["Student", "Staff"],
      scope_of_usage: "University",
      software_name: "CampusHealth360",
      use_description: "Student health records management and appointment scheduling across all campus clinics",
      vendor_website: "https://campushealth360.io",
      software_term: "3yr",
      estimated_spend: 22000,
      purchase_type: "new",
      funding_source: "SDSU stateside",
      college_division: "Division of Student Affairs",
      existing_requisition: true,
      needs_install_help: true,
      notify_list: ["mtorres@sdsu.edu", "healthit@sdsu.edu"],
      additional_details: "Requires integration with PeopleSoft student system. HIPAA BAA must be signed before go-live.",
    },
    it_review: {
      estimated_users: "100+",
      interaction_method: ["Web browser", "Mobile"],
      software_category: "Cloud",
      shares_data_with_campus_system: true,
      integration_explanation: "Connects to PeopleSoft student information system for enrollment and demographic data",
      sso_capable: "true",
      level_1_data: true,
      level_1_categories: ["HIPAA", "PII"],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: true,
      compliance_note: "HIPAA Business Associate Agreement required with vendor",
      vendor_privacy_policy_url: "https://campushealth360.io/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "100+ users, University scope",
      security_flag: true,
      security_flag_reason: "Level 1 data: HIPAA, PII",
      integration_flag: true,
      integration_flag_reason: "Shares data with campus system: PeopleSoft student information system",
      risk_level: "High",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
  },

  // --- Medium-risk classroom tool, ATI + Security triggered, no integration ---
  {
    request_id: "ccc-003",
    status: "Submitted",
    created_at: "2026-07-14T14:00:00Z",
    updated_at: "2026-07-14T14:00:00Z",
    requestor: {
      requested_for_name: "Priya Nair",
      requested_for_phone: "619-555-0303",
      requested_for_email: "pnair@sdsu.edu",
      department: "Engineering",
      user_types: ["Student", "Faculty"],
      scope_of_usage: "Classroom",
      software_name: "AutoCAD LT",
      use_description: "Engineering diagrams and technical drawings for undergraduate design courses",
      vendor_website: "https://autodesk.com/autocad-lt",
      software_term: "1yr",
      estimated_spend: 1200,
      purchase_type: "renewal",
      funding_source: "SDSU stateside",
      college_division: "College of Engineering",
      existing_requisition: false,
      needs_install_help: true,
      notify_list: ["pnair@sdsu.edu", "engr-it@sdsu.edu"],
      additional_details: "Used in ENGR 201 and ENGR 305. Student assignment files may contain project data.",
    },
    it_review: {
      estimated_users: "30-100",
      interaction_method: ["Computer"],
      software_category: "On-prem Local",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "false",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: true,
      level_2_categories: ["FERPA"],
      other_data_category: null,
      compliance_requirements: true,
      compliance_note: "Student assignment submissions may be subject to FERPA",
      vendor_privacy_policy_url: "https://autodesk.com/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "30-100 users, Classroom scope",
      security_flag: true,
      security_flag_reason: "Level 2 data: FERPA",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "Medium",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
  },
];
