// Mock API responses shaped exactly like the frozen DynamoDB data model.
// Replace fetch calls with real endpoints once Person 3's API is live.

export const MOCK_REQUESTS = [
  // --- Low-risk renewal, no flags ---
  // All three reviews still pending — no uploads yet.
  {
    request_id: "aaa-001",
    status: "ITReview",
    created_at: "2026-07-14T10:00:00Z",
    updated_at: "2026-07-14T11:00:00Z",
    requestor: {
      requested_for_name: "Jane Smith",
      requested_for_phone: "619-555-0101",
      requested_for_email: "jsmith@sdsu.edu",
      department: "College of Sciences",
      user_types: ["Faculty", "Staff"],
      scope_of_usage: "Research Lab",
      software_name: "ResearchTrack Pro",
      use_description: "Track lab experiment data and manage research team tasks",
      vendor_website: "https://researchtrackpro.com",
      software_term: "1yr",
      estimated_spend: 4500,
      purchase_type: "renewal",
      funding_source: "SDSU Research Foundation",
      college_division: "College of Sciences",
      existing_requisition: false,
      needs_install_help: false,
      notify_list: ["jsmith@sdsu.edu"],
      additional_details: "Used by 5 grad students and 2 faculty members.",
    },
    it_review: {
      estimated_users: "1-30",
      interaction_method: ["Computer"],
      software_category: "Cloud",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "not_sure",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: "https://researchtrackpro.com/privacy",
    },
    flags: {
      ati_flag: false,
      ati_flag_reason: "Under 30 users, Research Lab scope does not trigger ATI",
      security_flag: false,
      security_flag_reason: "No sensitive data categories identified",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "Low",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
    review_docs: {
      ati:         { status: "pending", message: "Review in progress, gathering documents", files: [] },
      itso:        { status: "pending", message: "Review in progress, gathering documents", files: [] },
      integration: { status: "pending", message: "Review in progress, gathering documents", files: [] },
    },
  },

  // --- High-risk new software, all three flags triggered ---
  // ATI + ITSO have documents uploaded; Integration completed with no documents.
  {
    request_id: "bbb-002",
    status: "AdditionalReview",
    created_at: "2026-07-13T09:00:00Z",
    updated_at: "2026-07-14T08:00:00Z",
    requestor: {
      requested_for_name: "Mark Torres",
      requested_for_phone: "619-555-0202",
      requested_for_email: "mtorres@sdsu.edu",
      department: "Student Affairs",
      user_types: ["Student", "Staff"],
      scope_of_usage: "University",
      software_name: "CampusHealth360",
      use_description: "Student health records management and appointment scheduling across all campus clinics",
      vendor_website: "https://campushealth360.io",
      software_term: "3yr",
      estimated_spend: 22000,
      purchase_type: "new",
      funding_source: "SDSU stateside",
      college_division: "Division of Student Affairs",
      existing_requisition: true,
      needs_install_help: true,
      notify_list: ["mtorres@sdsu.edu", "healthit@sdsu.edu"],
      additional_details: "Requires integration with PeopleSoft student system. HIPAA BAA must be signed before go-live.",
    },
    it_review: {
      estimated_users: "100+",
      interaction_method: ["Web browser", "Mobile"],
      software_category: "Cloud",
      shares_data_with_campus_system: true,
      integration_explanation: "Connects to PeopleSoft student information system for enrollment and demographic data",
      sso_capable: "true",
      level_1_data: true,
      level_1_categories: ["HIPAA", "PII"],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: true,
      compliance_note: "HIPAA Business Associate Agreement required with vendor",
      vendor_privacy_policy_url: "https://campushealth360.io/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "100+ users, University scope",
      security_flag: true,
      security_flag_reason: "Level 1 data: HIPAA, PII",
      integration_flag: true,
      integration_flag_reason: "Shares data with campus system: PeopleSoft student information system",
      ai_flag: true,
      ai_flag_reason: "AI-enabled automated decision system — California ADS inventory (AB 302)",
      risk_level: "High",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      // ITSO review already done; ATI + Integration still open.
      review_completions: { ati_flag: false, security_flag: true, integration_flag: false },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
    review_docs: {
      ati: {
        status: "complete",
        message: null,
        files: [
          { name: "privacy_policy.pdf", url: "https://example.s3.amazonaws.com/presigned/privacy_policy.pdf" },
          { name: "vpat.pdf",           url: "https://example.s3.amazonaws.com/presigned/vpat.pdf" },
        ],
      },
      itso: {
        status: "complete",
        message: null,
        files: [
          { name: "hecvat.pdf",           url: "https://example.s3.amazonaws.com/presigned/hecvat.pdf" },
          { name: "soc2.pdf",             url: "https://example.s3.amazonaws.com/presigned/soc2.pdf" },
          { name: "terms_of_service.pdf", url: "https://example.s3.amazonaws.com/presigned/terms_of_service.pdf" },
        ],
      },
      integration: { status: "no_docs", message: "No documents found", files: [] },
    },
  },

  // --- Medium-risk classroom tool, ATI + Security triggered, no integration ---
  // ITSO uploaded but no files (contact vendor); ATI and Integration still pending.
  {
    request_id: "ccc-003",
    status: "Submitted",
    created_at: "2026-07-14T14:00:00Z",
    updated_at: "2026-07-14T14:00:00Z",
    requestor: {
      requested_for_name: "Priya Nair",
      requested_for_phone: "619-555-0303",
      requested_for_email: "pnair@sdsu.edu",
      department: "Engineering",
      user_types: ["Student", "Faculty"],
      scope_of_usage: "Classroom",
      software_name: "AutoCAD LT",
      use_description: "Engineering diagrams and technical drawings for undergraduate design courses",
      vendor_website: "https://autodesk.com/autocad-lt",
      software_term: "1yr",
      estimated_spend: 1200,
      purchase_type: "renewal",
      funding_source: "SDSU stateside",
      college_division: "College of Engineering",
      existing_requisition: false,
      needs_install_help: true,
      notify_list: ["pnair@sdsu.edu", "engr-it@sdsu.edu"],
      additional_details: "Used in ENGR 201 and ENGR 305. Student assignment files may contain project data.",
    },
    it_review: {
      estimated_users: "30-100",
      interaction_method: ["Computer"],
      software_category: "On-prem Local",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "false",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: true,
      level_2_categories: ["FERPA"],
      other_data_category: null,
      compliance_requirements: true,
      compliance_note: "Student assignment submissions may be subject to FERPA",
      vendor_privacy_policy_url: "https://autodesk.com/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "30-100 users, Classroom scope",
      security_flag: true,
      security_flag_reason: "Level 2 data: FERPA",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "Medium",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "",
    },
    review_docs: {
      ati:         { status: "pending", message: "Review in progress, gathering documents", files: [] },
      itso:        { status: "no_docs", message: "No documents found. Contact vendor", files: [] },
      integration: { status: "pending", message: "Review in progress, gathering documents", files: [] },
    },
  },

  // --- Approved: ATI concern cleared via staff override ---
  // All reviews complete with documents.
  {
    request_id: "ddd-004",
    status: "Approved",
    created_at: "2026-07-10T09:00:00Z",
    updated_at: "2026-07-12T15:30:00Z",
    requestor: {
      requested_for_name: "Wei Chen",
      requested_for_phone: "619-555-0404",
      requested_for_email: "wchen@sdsu.edu",
      department: "Library",
      user_types: ["Student", "Public"],
      scope_of_usage: "College",
      software_name: "StackMap Wayfinding",
      use_description: "Interactive library shelf locator kiosk for the main library",
      vendor_website: "https://stackmap.com",
      software_term: "1yr",
      estimated_spend: 3000,
      purchase_type: "renewal",
      funding_source: "SDSU stateside",
      college_division: "University Library",
      existing_requisition: false,
      needs_install_help: false,
      notify_list: ["wchen@sdsu.edu"],
      additional_details: "Renewal of existing kiosk license.",
    },
    it_review: {
      estimated_users: "100+",
      interaction_method: ["Web browser"],
      software_category: "Cloud",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "not_sure",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: "https://stackmap.com/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "100+ users, College scope",
      security_flag: false,
      security_flag_reason: "No Level 1 or Level 2 data identified",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "Low",
    },
    admin: {
      overrides: { ati_flag: false, security_flag: null, integration_flag: null },
      override_reason: "Public kiosk already reviewed for accessibility last renewal cycle.",
      overridden_by: "jsmith@sdsu.edu",
      admin_notes: "ATI concern addressed via override. Approved — proceeds to Procurement outside this system.",
    },
    review_docs: {
      ati: {
        status: "complete",
        message: null,
        files: [
          { name: "vpat.pdf", url: "https://example.s3.amazonaws.com/presigned/vpat_stackmap.pdf" },
        ],
      },
      itso: {
        status: "complete",
        message: null,
        files: [
          { name: "soc2.pdf", url: "https://example.s3.amazonaws.com/presigned/soc2_stackmap.pdf" },
        ],
      },
      integration: { status: "no_docs", message: "No documents found", files: [] },
    },
  },

  // --- In additional review: shares data with a campus system (integration) ---
  // Integration has a document; ATI and ITSO still pending (not flagged).
  {
    request_id: "eee-005",
    status: "AdditionalReview",
    created_at: "2026-06-20T09:00:00Z",
    updated_at: "2026-07-01T12:00:00Z",
    requestor: {
      requested_for_name: "Alicia Gomez",
      requested_for_phone: "619-555-0505",
      requested_for_email: "agomez@sdsu.edu",
      department: "Enrollment Services",
      user_types: ["Staff"],
      scope_of_usage: "Department",
      software_name: "DocuSign",
      use_description: "Electronic signatures for enrollment paperwork",
      vendor_website: "https://docusign.com",
      software_term: "1yr",
      estimated_spend: 1800,
      purchase_type: "renewal",
      funding_source: "SDSU stateside",
      college_division: "Division of Student Affairs",
      existing_requisition: true,
      needs_install_help: false,
      notify_list: ["agomez@sdsu.edu"],
      additional_details: "Annual renewal, PCC purchase.",
    },
    it_review: {
      estimated_users: "1-30",
      interaction_method: ["Web browser"],
      software_category: "Cloud",
      shares_data_with_campus_system: true,
      integration_explanation: "Pulls enrollee names and IDs from PeopleSoft to pre-fill envelopes",
      sso_capable: "true",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: "https://docusign.com/privacy",
    },
    flags: {
      ati_flag: false,
      ati_flag_reason: "Below ATI thresholds",
      security_flag: false,
      security_flag_reason: "No Level 1 or Level 2 data identified",
      integration_flag: true,
      integration_flag_reason: "Pulls enrollee names and IDs from PeopleSoft to pre-fill envelopes",
      risk_level: "Low",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "Integration Services confirming read-only PeopleSoft access scope.",
    },
    review_docs: {
      ati:  { status: "pending", message: "Review in progress, gathering documents", files: [] },
      itso: { status: "pending", message: "Review in progress, gathering documents", files: [] },
      integration: {
        status: "complete",
        message: null,
        files: [
          { name: "architecture_notes.pdf", url: "https://example.s3.amazonaws.com/presigned/arch_docusign.pdf" },
        ],
      },
    },
  },

  // --- Denied: security review did not pass ---
  // ITSO completed with no documents; others pending.
  {
    request_id: "fff-006",
    status: "Denied",
    created_at: "2026-06-15T09:00:00Z",
    updated_at: "2026-06-22T16:00:00Z",
    requestor: {
      requested_for_name: "Devon Marks",
      requested_for_phone: "619-555-0606",
      requested_for_email: "dmarks@sdsu.edu",
      department: "Athletics",
      user_types: ["Staff"],
      scope_of_usage: "Department",
      software_name: "QuickShare Cloud Drive",
      use_description: "General file sharing for the athletics department",
      vendor_website: "https://quickshare.example.com",
      software_term: "1yr",
      estimated_spend: 900,
      purchase_type: "new",
      funding_source: "SDSU stateside",
      college_division: "Intercollegiate Athletics",
      existing_requisition: false,
      needs_install_help: false,
      notify_list: ["dmarks@sdsu.edu"],
      additional_details: "No SOC 2 report available from vendor on request.",
    },
    it_review: {
      estimated_users: "30-100",
      interaction_method: ["Web browser", "Mobile"],
      software_category: "Cloud",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "false",
      level_1_data: true,
      level_1_categories: ["PII"],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: null,
    },
    flags: {
      ati_flag: false,
      ati_flag_reason: "Below ATI thresholds",
      security_flag: true,
      security_flag_reason: "Level 1 data: PII",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      risk_level: "High",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      override_reason: "",
      overridden_by: "",
      admin_notes: "No SOC 2, unresolved CVEs, no privacy policy on file. Vendor risk review failed — request denied.",
    },
    review_docs: {
      ati:         { status: "pending", message: "Review in progress, gathering documents", files: [] },
      itso:        { status: "no_docs", message: "No documents found. Contact vendor", files: [] },
      integration: { status: "pending", message: "Review in progress, gathering documents", files: [] },
    },
  },

  // --- In additional review: 100+ users, public-facing scope (ATI) ---
  // ATI has no docs yet; ITSO and Integration still pending.
  {
    request_id: "ggg-007",
    status: "AdditionalReview",
    created_at: "2026-07-08T09:00:00Z",
    updated_at: "2026-07-09T13:00:00Z",
    requestor: {
      requested_for_name: "Sofia Reyes",
      requested_for_phone: "619-555-0707",
      requested_for_email: "sreyes@sdsu.edu",
      department: "Admissions",
      user_types: ["Student", "Public"],
      scope_of_usage: "University",
      software_name: "CampusTour VR",
      use_description: "Virtual campus tour kiosk for prospective students and visitors",
      vendor_website: "https://campustourvr.example.com",
      software_term: "1yr",
      estimated_spend: 5200,
      purchase_type: "new",
      funding_source: "SDSU stateside",
      college_division: "Enrollment Services",
      existing_requisition: false,
      needs_install_help: true,
      notify_list: ["sreyes@sdsu.edu"],
      additional_details: "Public-facing kiosk in the welcome center.",
    },
    it_review: {
      estimated_users: "100+",
      interaction_method: ["Computer", "Web browser"],
      software_category: "Cloud",
      shares_data_with_campus_system: false,
      integration_explanation: null,
      sso_capable: "not_sure",
      level_1_data: false,
      level_1_categories: [],
      level_2_data: false,
      level_2_categories: [],
      other_data_category: null,
      compliance_requirements: false,
      compliance_note: null,
      vendor_privacy_policy_url: "https://campustourvr.example.com/privacy",
    },
    flags: {
      ati_flag: true,
      ati_flag_reason: "100+ users, University scope",
      security_flag: false,
      security_flag_reason: "No Level 1 or Level 2 data identified",
      integration_flag: false,
      integration_flag_reason: "No campus system integration required",
      ai_flag: false,
      ai_flag_reason: "No AI capabilities reported",
      risk_level: "Low",
    },
    admin: {
      overrides: { ati_flag: null, security_flag: null, integration_flag: null },
      review_completions: { ati_flag: false, security_flag: false, integration_flag: false },
      override_reason: "",
      overridden_by: "",
      admin_notes: "Awaiting ATI coordinator sign-off on kiosk screen-reader support.",
    },
    review_docs: {
      ati:         { status: "no_docs", message: "No documents found. Contact vendor", files: [] },
      itso:        { status: "pending", message: "Review in progress, gathering documents", files: [] },
      integration: { status: "pending", message: "Review in progress, gathering documents", files: [] },
    },
  },
];
